# Generated by Django 5.0.1 on 2024-01-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablesize',
            old_name='discount_price',
            new_name='regular_price',
        ),
    ]
