# Generated by Django 4.2.7 on 2024-02-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablesize',
            name='weight',
        ),
    ]
