# Generated by Django 5.0.1 on 2024-01-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_discount_price_availablesize_regular_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesize',
            options={'ordering': ('discount_price',), 'verbose_name': 'Available Size', 'verbose_name_plural': 'Available Sizes'},
        ),
        migrations.RenameField(
            model_name='availablesize',
            old_name='sale_price',
            new_name='discount_price',
        ),
    ]
