# Generated by Django 4.2.7 on 2024-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_availablesize_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text=' The recommended size is 120x120 pixels.', null=True, upload_to='Catrgory/img'),
        ),
    ]
