# Generated by Django 4.2.7 on 2024-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
