# Generated by Django 5.0.1 on 2024-01-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_availablesize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablesize',
            name='unit',
            field=models.CharField(blank=True, choices=[('34x14', '34x14'), ('42x14', '42x14'), ('16x14', '16x14')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
