# Generated by Django 5.0.1 on 2024-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_availablesize_unit_alter_availablesize_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_p',
            field=models.ImageField(default=1, help_text=' The recommended size is 220x220 pixels.', upload_to='products/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text=' The recommended size is 120x120 pixels.', upload_to='products/img'),
        ),
    ]
