# Generated by Django 5.0.1 on 2024-01-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='available',
            options={'ordering': ('sale_price',), 'verbose_name': 'Available ', 'verbose_name_plural': 'Available'},
        ),
        migrations.AlterModelOptions(
            name='availablesize',
            options={'ordering': ('sale_price',), 'verbose_name': 'Available Size', 'verbose_name_plural': 'Available Sizes'},
        ),
        migrations.RenameField(
            model_name='available',
            old_name='discount_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='availablesize',
            old_name='discount_price',
            new_name='sale_price',
        ),
    ]
